key_path: path/to/ssh_key.pem
region_name: eu-west-3
log_file: logs/main_log.log
instance_status_log: logs/instance_status.log
hosts_ini_file: files/hosts.ini
connection_helper_file: files/connection_helper